version: '3.4'

services:
  redis:
        image: "redis:alpine"
        ports:
          - "6379:6379"
  mongodb:
        image: "mongo"
        ports:
          - "27017:27017"
  newsapp.api:
    image: ${DOCKER_REGISTRY-}newsappapi
    build:
      context: .
      dockerfile: src\NewsApp.Api\Dockerfile
    restart: always
    depends_on:
            - mongodb
            - redis
    ports:
      - "18200:80"